#!/bin/sh
#
# lcd        Starts lcd.
#

start() {
	echo 3 > /proc/sys/vm/drop_caches
	sleep 0.3
	sync
	echo -e "\033[9;0]" > /dev/tty0
	sleep 0.3
	sync
}
stop() {
	echo "Stopping screen..."
	sync
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

