#!/bin/sh
#
# psplash        Starts psplash.
#

start() {
	sync
	rm -rf /tmp/psplash_fifo
	sync
	echo "Starting psplash..."
	psplash &
	sleep 0.7
	sync
	echo "PROGRESS 1" > /tmp/psplash_fifo
	sync
	echo "PROGRESS 3" > /tmp/psplash_fifo
	sync
}
stop() {
	echo "Stopping psplash..."
	sync
	echo "PROGRESS 3" > /tmp/psplash_fifo
	sleep 0.7
	sync
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

