#!/bin/sh
#
# psplash        Starts psplash.
#

start() {
	sync
	rm -rf /tmp/psplash_fifo
	echo "Starting psplash..."
	psplash &
	sleep 1
	echo "PROGRESS 5" > /tmp/psplash_fifo
	echo "MSG Starting" > /tmp/psplash_fifo
}
stop() {
	echo "Stopping psplash..."
	echo "MSG Shutdown" > /tmp/psplash_fifo
	sleep 1
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

