#!/bin/sh
#
# lcd        Starts umu.
#

start() {
	sync
	echo "PROGRESS 5" > /tmp/psplash_fifo
	echo "Starting umu..."
	echo 1 > /proc/gpio/gpo-3
	sync
	echo "PROGRESS 10" > /tmp/psplash_fifo
	sync
}
stop() {
	echo "Stopping umu..."
	echo 0 > /proc/gpio/gpo-3
	sync
	echo "PROGRESS 10" > /tmp/psplash_fifo
	sync
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

