#!/bin/sh
#
# bluetooth        Starts bluetooth.
#


start() {
	echo "Resetting bluetooth"
	echo 0 > /proc/gpio/bt-en
	echo 1 > /proc/gpio/bt-en
	sleep 1
	sync
	echo "Loading firmware..."
	hciattach -s 115200 /dev/ttymxc2 texas
	echo "Bluetooth firmware loaded..."
	echo "PROGRESS 40" > /tmp/psplash_fifo
	echo "MSG Bluetooth" > /tmp/psplash_fifo
}
stop() {
	echo "Stopping bluetooth"
	echo "PROGRESS 60" > /tmp/psplash_fifo
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

