#!/bin/sh
#
# avicon        Starts avicon.
#


start() {
	echo "Starting Avicon...";
	echo "PROGRESS 90" > /tmp/psplash_fifo
}
stop() {
	echo "Stopping avicon...";
	echo "PROGRESS 90" > /tmp/psplash_fifo
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

