#!/bin/sh
#
# psplash        Starts psplash.
#

# Make sure the psplash progam exists
[ -f /usr/bin/psplash ] || exit 0

start() {
	sync
	echo "PROGRESS 100" > /tmp/psplash_fifo
	sync
	sleep 0.1
	echo "QUIT" > /tmp/psplash_fifo
	sync
	sleep 0.1
}
stop() {
	sync
	rm -rf /tmp/psplash_fifo
	sync
	psplash &
	sleep 0.5
	sync
	echo "PROGRESS 100" > /tmp/psplash_fifo
	sync
	echo "MSG Shutdown" > /tmp/psplash_fifo
	sync
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

